### ISSUE TITLE
CreateDeck: Small bug: You should not be able to change the deck name after finishing, unless you click 'create another deck' [see description]

### ISSUE THREAD

**Issue by akerfel** [akerfel/glossary-pal#22]
Once the following [image](https://user-images.githubusercontent.com/45148959/205292105-3ac2ce09-e732-4ab3-96a3-dfab1aa1451c.png) shows, you should not be able to change the deck name until you click "**Create Another Deck**", since currently the name on the popup will dynamically change, which could be confusing for users (they would be unsure what the list name was actually saved as). Also you should probably not be able to delete words from the list either, since it does not do anything (also confusing).

A simpler solution would be to just redirect the user to the home page when they click "Create Deck"

**Comment by cadye** [comment]
fixed by creating a post-createDeck View, where nothing is editable.
